-- Generated by .dev-test/embed_tools.js -- do not edit by hand.
--
-- The converters have to travel inside the mod because Factorio Lua cannot
-- read a file: helpers only writes. Each text below is a byte-for-byte copy of
-- the file named beside it, and test.lua fails if the two ever differ, so the
-- copy cannot quietly go stale. Re-run the generator after editing a converter.
return {
  {
    path = "tools/json-to-string.ps1",
    text = [==[<#
.SYNOPSIS
  Turn the exported .json files back into Factorio blueprint strings.

.DESCRIPTION
  The mod writes two files per blueprint: a .txt with the exchange string and a
  .json with the same payload, pretty printed for git. This script rebuilds an
  importable string from the .json, so an edited .json can go back into the game.

  The payload is never re-serialized. The bytes of the file are what get
  compressed, which keeps numbers exactly as Factorio wrote them: ConvertTo-Json
  in PowerShell 5.1 renders doubles with the current culture ("0,5" under a
  Russian locale), which would produce JSON the game cannot read.

  The _export field (the label with its markup, plus the chain of book names)
  is dropped: it is export metadata, not blueprint data. _book.json sidecars
  are skipped for the same reason.

  Output is the classic form "0" + base64(zlib(json)), which every supported
  Factorio accepts. -Raw prints the plain JSON instead; 2.0 and newer also
  accept that, and it needs no compression at all.

.PARAMETER In
  A .json file, or a directory that is searched recursively.

.PARAMETER Out
  File to write when In is one file. Directory to mirror into when In is many
  files. Without -Out a single file is printed to stdout, and more than one is
  an error so nothing is silently dropped.

.PARAMETER Raw
  Emit uncompressed JSON instead of the compressed string.

.PARAMETER NoValidate
  Skip the parse check. The check only proves the input is well formed JSON; it
  does not change the bytes that are written.

.EXAMPLE
  .\json-to-string.ps1 .\009_Roboport.json | Set-Clipboard

.EXAMPLE
  .\json-to-string.ps1 . -Out ..\rebuilt
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory = $true, Position = 0)][string]$In,
  [Parameter(Position = 1)][string]$Out,
  [switch]$Raw,
  [switch]$NoValidate
)

Set-StrictMode -Version 2
$ErrorActionPreference = "Stop"

function Read-JsonText([string]$Path) {
  # Get-Content without -Encoding Byte would apply the ANSI code page on a
  # PowerShell 5.1 that has no BOM to read, mangling every non-ASCII name.
  $bytes = Get-Content -LiteralPath $Path -Encoding Byte -ReadCount 0
  return [System.Text.Encoding]::UTF8.GetString($bytes)
}

function Remove-ExportField([string]$Text) {
  # _export is always the first key (an underscore sorts before letters) and
  # holds only strings and an array of strings, so it contains no nested
  # object. The closing pattern below cannot appear inside those values.
  $pattern = '(?s)"_export"\s*:\s*\{.*?\r?\n\s*\},?'
  $stripped = [regex]::Replace($Text, $pattern, "")
  return $stripped.Trim()
}

function Test-Json([string]$Text) {
  # JavaScriptSerializer, not ConvertFrom-Json: the cmdlet in 5.1 is slower on
  # big payloads. Its default length cap is 2 MB and a real library holds
  # circuit books of 3 to 6.7 MB, which are perfectly valid -- the cap has to go
  # up or those files look corrupt. Each setting is guarded on its own: an
  # assignment that throws must not make a valid file fail the check.
  try {
    Add-Type -AssemblyName System.Web.Extensions
    $serializer = New-Object System.Web.Script.Serialization.JavaScriptSerializer
    try { $serializer.MaxJsonLength = [int]::MaxValue } catch { }
    # MaxDepth is not a settable property on every .NET build. The default is
    # 100 and the deepest blueprint in a real 637-record library nests 13
    # levels, so it is left alone.
    $null = $serializer.DeserializeObject($Text)
    return $true
  } catch {
    return $false
  }
}

function Get-Adler32([byte[]]$Data) {
  $a = 1; $b = 0
  foreach ($byte in $Data) {
    $a = ($a + $byte) % 65521
    $b = ($b + $a) % 65521
  }
  return @([byte](($b -shr 8) -band 0xFF), [byte]($b -band 0xFF),
          [byte](($a -shr 8) -band 0xFF), [byte]($a -band 0xFF))
}

function Compress-Zlib([byte[]]$Data) {
  # DeflateStream writes raw DEFLATE. Factorio expects zlib: two header bytes,
  # the same DEFLATE stream, then Adler-32 of the uncompressed data.
  $memory = New-Object System.IO.MemoryStream
  $deflater = New-Object System.IO.Compression.DeflateStream(
    $memory, [System.IO.Compression.CompressionMode]::Compress, $true)
  $deflater.Write($Data, 0, $Data.Length)
  $deflater.Dispose()
  $deflated = $memory.ToArray()
  $memory.Dispose()

  $zlib = New-Object System.IO.MemoryStream
  $zlib.WriteByte(0x78)
  $zlib.WriteByte(0x9C)
  $zlib.Write($deflated, 0, $deflated.Length)
  $tail = Get-Adler32 $Data
  $zlib.Write($tail, 0, $tail.Length)
  $out = $zlib.ToArray()
  $zlib.Dispose()
  return $out
}

function Get-Files([string]$Path) {
  if (Test-Path -LiteralPath $Path -PathType Leaf) {
    return ,@(Get-Item -LiteralPath $Path)
  }
  if (-not (Test-Path -LiteralPath $Path -PathType Container)) {
    throw "no such file or directory: $Path"
  }
  # Square brackets appear in exported names, so every path access has to stay
  # literal; -Filter is safe because it matches names, not paths.
  $all = Get-ChildItem -LiteralPath $Path -Recurse -Filter "*.json" -File
  return @($all | Where-Object {
    $_.Name -notlike "_*" -and $_.Name -ne "manifest.json"
  })
}

function Convert-One($File, [string]$Root) {
  $text = Remove-ExportField (Read-JsonText $File.FullName)
  if ($text.Length -eq 0) {
    throw "nothing left after removing _export: $($File.FullName)"
  }
  if (-not $NoValidate -and -not (Test-Json $text)) {
    throw "not valid JSON: $($File.FullName)"
  }
  if ($Raw) {
    return $text
  }
  $bytes = [System.Text.Encoding]::UTF8.GetBytes($text)
  return "0" + [System.Convert]::ToBase64String((Compress-Zlib $bytes))
}

function Get-RelativePath([string]$Root, [string]$Full) {
  $rootFull = (Resolve-Path -LiteralPath $Root).Path.TrimEnd('\', '/')
  if ($Full.Length -le $rootFull.Length -or
      $Full.Substring(0, $rootFull.Length) -ne $rootFull) {
    return Split-Path -Leaf $Full
  }
  return $Full.Substring($rootFull.Length + 1).TrimStart('\', '/')
}

$files = Get-Files $In
if ($files.Count -eq 0) {
  Write-Error "no .json files found under $In"
  exit 1
}

$failed = 0
if ($files.Count -eq 1 -and -not $Out) {
  # Clipboard case: the string alone, nothing else on stdout.
  Write-Output (Convert-One $files[0] $In)
  exit 0
}

if ($files.Count -gt 1 -and -not $Out) {
  Write-Error "$($files.Count) files: give -Out <directory> (or a single file to get stdout)"
  exit 1
}

$outIsDir = (Test-Path -LiteralPath $Out -PathType Container) -or
            ($Out -match '[\\/]$') -or $files.Count -gt 1
if ($outIsDir) {
  if (-not (Test-Path -LiteralPath $Out)) {
    New-Item -ItemType Directory -Path $Out | Out-Null
  }
}

foreach ($file in $files) {
  try {
    $result = Convert-One $file $In
  } catch {
    Write-Warning ("failed: " + $_.Exception.Message)
    $failed++
    continue
  }
  if ($outIsDir) {
    $rel = Get-RelativePath $In $file.FullName
    $targetRel = if ($Raw) { $rel } else { [System.IO.Path]::ChangeExtension($rel, ".txt") }
    $target = Join-Path $Out $targetRel
    $dir = Split-Path -Parent $target
    if (-not (Test-Path -LiteralPath $dir)) {
      New-Item -ItemType Directory -Path $dir | Out-Null
    }
    [System.IO.File]::WriteAllText($target, $result,
      (New-Object System.Text.UTF8Encoding($false)))
    Write-Output ("wrote " + $targetRel)
  } elseif ($files.Count -eq 1) {
    [System.IO.File]::WriteAllText($Out, $result,
      (New-Object System.Text.UTF8Encoding($false)))
    Write-Output ("wrote " + $Out)
  }
}

if ($failed -gt 0) {
  Write-Error "$failed of $($files.Count) files failed"
  exit 1
}
]==],
  },
  {
    path = "tools/json-to-string.sh",
    text = [==[#!/usr/bin/env bash
#
# Turn the exported .json files back into Factorio blueprint strings.
#
# The mod writes two files per blueprint: a .txt with the exchange string and a
# .json with the same payload, pretty printed for git. This script rebuilds an
# importable string from the .json, so an edited .json can go back into the game.
#
# The payload is never re-serialized -- the bytes of the file are what get
# compressed, which keeps every number exactly as Factorio wrote it.
#
# The _export field (label with its markup, plus the chain of book names) is
# dropped, and _book.json sidecars are skipped: both are export metadata, not
# blueprint data.
#
# Usage: json-to-string.sh [options] IN [OUT]
#   IN   a .json file, or a directory searched recursively
#   OUT  file to write for a single IN, directory to mirror into for many
#
# Options:
#   --raw           emit plain JSON instead of "0"+base64(zlib(json))
#   --no-validate   skip the parse check (needs python3; it changes no bytes)
#
# With one input file and no OUT the string goes to stdout, so
#   ./json-to-string.sh 009_Roboport.json | xclip -selection clipboard
# works as expected.

set -euo pipefail

raw=0
validate=1

die() { printf 'error: %s\n' "$1" >&2; exit 1; }

usage() { sed -n '3,26p' "$0" | sed 's/^# \{0,1\}//'; }

raw_json() {
  # _export is always the first key (an underscore sorts before letters) and
  # holds only strings and an array of strings, so no value can look like the
  # line that closes it.
  awk '
    BEGIN { state = 0 }
    state == 0 {
      if ($0 ~ /"_export"[ \t]*:/) { state = 1; next }
      print; next
    }
    state == 1 {
      if ($0 ~ /^[ \t]*\},?[ \t]*$/) { state = 2 }
      next
    }
    { print }
  ' "$1"
}

adler32_octal() {
  # zlib closes its stream with Adler-32 of the uncompressed data. Only POSIX
  # awk here: no strtonum(), no and(), no rshift() -- mawk and busybox have
  # none of them.
  od -An -v -tx1 "$1" | tr -s ' \t\n' ' ' | awk '
    BEGIN { a = 1; b = 0 }   # Adler-32 accumulates from 1, not from 0
    function hexval(c) {
      if (c >= "0" && c <= "9") return c + 0
      return index("abcdef", c) + 9
    }
    {
      for (i = 1; i <= NF; i++) {
        v = hexval(substr($i, 1, 1)) * 16 + hexval(substr($i, 2, 1))
        a = (a + v) % 65521
        b = (b + a) % 65521
      }
    }
    END {
      n = (b * 65536 + a) % 4294967296
      for (s = 3; s >= 0; s--) printf "\\%03o", int(n / (256 ^ s)) % 256
    }
  ' | tr -d "\n"
}

to_string() {
  local file="$1"
  # The leading "0" is the format version byte Factorio puts in front of the
  # base64; without it the game reads the string as corrupt.
  printf '0'
  # gzip stores the name and mtime only with -n; without it the 10-byte header
  # would hold them and the slice below would cut into the DEFLATE stream.
  # head -c -8 drops the CRC32 and ISIZE that gzip appends but zlib does not use.
  {
    printf '%b' '\170\234'
    gzip -n -9 -c "$file" | tail -c +11 | head -c -8
    printf '%b' "$(adler32_octal "$file")"
  } | base64 -w0
}

collect() {
  local target="$1"
  if [ -f "$target" ]; then
    printf '%s\n' "$target"
  elif [ -d "$target" ]; then
    find "$target" -type f -name '*.json' \
      ! -name '_*' ! -name 'manifest.json' | LC_ALL=C sort
  else
    die "no such file or directory: $target"
  fi
}

relative() {
  local root="$1" full="$2"
  local prefix="${root%/}/"
  case "$full" in
    "$prefix"*) printf '%s\n' "${full#"$prefix"}" ;;
    *)          basename "$full" ;;
  esac
}

# Options may appear before or after the paths. A loop that stopped at the
# first non-option would silently ignore --raw in "script.sh IN OUT --raw" and
# write compressed output into a directory the user asked to be plain JSON.
positional=()
while [ $# -gt 0 ]; do
  case "$1" in
    --raw) raw=1 ;;
    --no-validate) validate=0 ;;
    -h|--help) usage; exit 0 ;;
    -*) die "unknown option: $1" ;;
    *) positional+=("$1") ;;
  esac
  shift
done

[ ${#positional[@]} -ge 1 ] || { usage >&2; die "an input path is required"; }
in_path="${positional[0]}"
out_path="${positional[1]:-}"

mapfile -t files < <(collect "$in_path")
[ "${#files[@]}" -gt 0 ] || die "no .json files found under $in_path"

tmp=""
cleanup() { [ -n "$tmp" ] && rm -f "$tmp"; }
trap cleanup EXIT

process() {
  # Write the payload to a real file: python3 wants a path, and the compressor
  # reads from a file anyway.
  local src="$1" dest="$2"
  raw_json "$src" > "$tmp"
  if [ "$validate" -eq 1 ]; then
    if command -v python3 >/dev/null 2>&1; then
      python3 -c 'import json,sys
with open(sys.argv[1], encoding="utf-8") as fh: json.load(fh)' "$tmp" \
        || { printf 'error: not valid JSON: %s\n' "$src" >&2; return 1; }
    else
      printf 'note: python3 is missing, the JSON was not validated\n' >&2
      validate=0
    fi
  fi
  if [ "$raw" -eq 1 ]; then
    cat "$tmp" > "$dest"
  else
    to_string "$tmp" > "$dest"
  fi
}

if [ "${#files[@]}" -eq 1 ] && [ -z "$out_path" ]; then
  tmp="$(mktemp)"
  process "${files[0]}" /dev/stdout
  exit 0
fi

[ -n "$out_path" ] || die "${#files[@]} files: give OUT (a directory) to write them"

tmp="$(mktemp)"
failed=0
count=0
for file in "${files[@]}"; do
  if [ "${#files[@]}" -eq 1 ]; then
    dest="$out_path"
    mkdir -p "$(dirname "$dest")"
  else
    rel="$(relative "$in_path" "$file")"
    if [ "$raw" -eq 1 ]; then
      dest="$out_path/$rel"
    else
      dest="$out_path/${rel%.json}.txt"
    fi
    mkdir -p "$(dirname "$dest")"
  fi
  if process "$file" "$dest"; then
    printf 'wrote %s\n' "$dest"
    count=$((count + 1))
  else
    printf 'failed: %s\n' "$file" >&2
    failed=$((failed + 1))
  fi
done

if [ "$failed" -gt 0 ]; then
  die "$failed of $((count + failed)) files failed"
fi
]==],
  },
}
