"use strict";
/*
 * Regenerate scripts/tools.lua from the converter sources.
 *
 *   node .dev-test/embed_tools.js
 *
 * Factorio Lua has no file-read API (helpers only writes), so the only way to
 * hand the converters to the user next to the exports is to carry their text
 * inside the mod. That means a second copy of every script, which drifts unless
 * something ties the two together: test.lua compares the embedded text with the
 * file on disk and fails when they differ. Run this after editing a converter.
 */
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const sources = ["tools/json-to-string.ps1", "tools/json-to-string.sh"];
const target = path.join(root, "scripts", "tools.lua");

// Long brackets with two equals signs, because the scripts contain "[" and "]"
// and a backslash in a regular expression -- a plain [[ ]] string would eat the
// backslash. Only the exact closing sequence would end the string early, so a
// lone "]]" inside is fine.
function luaString(text) {
  const open = "[==[";
  const close = "]==]";
  if (text.includes(close)) {
    throw new Error("text contains " + close + ", pick more '=' signs");
  }
  return open + text + close;
}

const entries = sources.map((rel) => {
  const text = fs.readFileSync(path.join(root, rel), "utf8");
  if (text.includes("\r")) {
    throw new Error(rel + " has CRLF; the mod would write CRLF and bash would refuse it");
  }
  return '  {\n    path = "' + rel + '",\n    text = ' + luaString(text) + ",\n  },";
});

const out = [
  "-- Generated by .dev-test/embed_tools.js -- do not edit by hand.",
  "--",
  "-- The converters have to travel inside the mod because Factorio Lua cannot",
  "-- read a file: helpers only writes. Each text below is a byte-for-byte copy of",
  "-- the file named beside it, and test.lua fails if the two ever differ, so the",
  "-- copy cannot quietly go stale. Re-run the generator after editing a converter.",
  "return {",
  entries.join("\n"),
  "}",
  "",
].join("\n");

fs.writeFileSync(target, out, "utf8");
const size = Buffer.byteLength(out, "utf8");
console.log("wrote scripts/tools.lua (" + size + " bytes, " + sources.length + " tools)");
